### ISSUE TITLE
管道类型可否支持QMSG

### ISSUE THREAD

**Issue by homeworkkun** [kentxxq/pusher#1]

**Comment by kentxxq** [comment]
webhook类型满足你的需求么?

创建一个webhook类型的管道, 地址是`https://qmsg.zendee.cn/jsend/你的key`  创建房间,关联这个管道
POST发送信息
```shell
curl -X POST https://pusher.kentxxq.com/pusher.webapi/Room/SendMessageByPost/你的房间code \
     -H "Content-Type: application/json" \
     -d '{"msg":"123\n你好"}'
```

**Comment by homeworkkun** [comment]
感谢您，昨天没鼓捣明白~

**Comment by homeworkkun** [comment]
> webhook类型满足你的需求么?
> 
> 创建一个webhook类型的管道, 地址是`https://qmsg.zendee.cn/jsend/你的key` 创建房间,关联这个管道 POST发送信息
> 
> ```shell
> curl -X POST https://pusher.kentxxq.com/pusher.webapi/Room/SendMessageByPost/你的房间code \
>      -H "Content-Type: application/json" \
>      -d '{"msg":"123\n你好"}'
> ```

您好我这两天忙，现在才试了下……我的需求是，把vikunja的webhook功能发送的内容以特定格式使用qmsg转发：
{"event_name":"task.updated","time":"2024-09-29T02:35:57.830038335Z","data":{"doer":{"id":1,"name":"作业君","username":"homeworkkun","created":"2024-09-28T13:11:37Z","updated":"2024-09-28T13:13:03Z"},"task":{"id":5,"title":"任务1","description":"","done":true,"done_at":"2024-09-29T02:35:57Z","due_date":"0001-01-01T00:00:00Z","reminders":null,"project_id":1,"repeat_after":0,"repeat_mode":0,"priority":0,"start_date":"0001-01-01T00:00:00Z","end_date":"0001-01-01T00:00:00Z","assignees":null,"labels":null,"hex_color":"","percent_done":0,"identifier":"#4","index":4,"related_tasks":{},"attachments":null,"cover_image_attachment_id":0,"is_favorite":false,"created":"2024-09-29T01:51:27Z","updated":"2024-09-29T02:35:57Z","bucket_id":0,"position":0,"reactions":null,"created_by":{"id":1,"name":"作业君","username":"homeworkkun","created":"2024-09-28T13:11:37Z","updated":"2024-09-28T13:13:03Z"}}}}

比如这个，用企业微信的管道可以正常推送
![image](https://github.com/user-attachments/assets/568f865b-2dab-42b8-9e5c-c71b6f1b8e14)
QMSG的话好像做不到

**Comment by kentxxq** [comment]
@homeworkkun 

使用webhook管道,你的自定义模板应该是这样
```json
{
  "msg":"{{event_name}} \n 任务: {{title}} \n {{description}}"
}
```

确实有点复杂(抽象...), 所以我新加了Qmsg管道, 你把管道类型改成Qmsg吧
